"use client";
import Link from "next/link";import{useEffect,useState}from"react";
type Json=Record<string,any>;function when(v?:string){if(!v)return"—";try{return new Date(v).toLocaleString()}catch{return v}}
export default function InboxClient(){const[data,setData]=useState<Json>({messages:[],alerts:[]});const[loading,setLoading]=useState(true);const[view,setView]=useState<"all"|"messages"|"alerts">("all");
async function load(){setLoading(true);try{const r=await fetch("/api/admin/inbox",{cache:"no-store"});const p=await r.json().catch(()=>null);if(r.ok&&p?.ok)setData(p)}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
const messages=Array.isArray(data.messages)?data.messages:[],alerts=Array.isArray(data.alerts)?data.alerts:[];
async function openMessage(item:Json){if(item.unread){await fetch("/api/admin/inbox/read",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messageId:item.id})});setData((current:Json)=>({...current,messages:(current.messages||[]).map((m:Json)=>m.id===item.id?{...m,unread:false}:m),unreadCount:Math.max(0,Number(current.unreadCount||0)-1)}))}window.location.assign(`/admin/projects?project=${encodeURIComponent(item.projectId)}`)}
return <main className="admin-inbox"><header className="admin-directory-head"><div><span>LINETECH / INBOX</span><h1>Operations inbox.</h1><p>Client conversations and operational risks in one queue.</p></div><button type="button" onClick={()=>void load()}>Refresh</button></header>
<div className="admin-inbox-summary"><div><span>UNREAD CLIENT MESSAGES</span><strong>{Number(data.unreadCount||0)}</strong></div><div><span>OPERATIONAL ALERTS</span><strong>{alerts.length}</strong></div><div><span>PAST DUE</span><strong>{alerts.filter((x:Json)=>x.reason==="Payment past due").length}</strong></div><div><span>OVERDUE DELIVERY</span><strong>{alerts.filter((x:Json)=>x.reason==="Delivery overdue").length}</strong></div></div>
<nav className="admin-inbox-tabs">{(["all","messages","alerts"] as const).map(x=><button key={x} className={view===x?"is-active":""} onClick={()=>setView(x)}>{x}</button>)}</nav>
{loading?<p className="admin-overview-empty">Loading inbox…</p>:<div className="admin-inbox-grid">
{(view==="all"||view==="alerts")&&<section><div className="admin-overview-panel-head"><div><span>PRIORITY QUEUE</span><h2>Needs attention.</h2></div></div><div className="admin-inbox-list">{alerts.map((item:Json)=><Link key={item.id} className={`priority-${item.priority}`} href={item.projectId?`/admin/projects?project=${encodeURIComponent(item.projectId)}`:"/admin/billing"}><i/><div><span>{item.clientName}</span><strong>{item.reason}</strong><p>{item.projectTitle}</p></div><aside>{item.amount?`$${Number(item.amount).toLocaleString()} due`:item.dueDate?when(item.dueDate):"OPEN"}<b>→</b></aside></Link>)}{!alerts.length&&<p className="admin-overview-empty">No operational alerts.</p>}</div></section>}
{(view==="all"||view==="messages")&&<section><div className="admin-overview-panel-head"><div><span>CLIENT MESSAGES</span><h2>Latest conversations.</h2></div></div><div className="admin-inbox-list">{messages.map((item:Json)=><button key={item.id} type="button" className={item.unread?"is-unread":""} onClick={()=>void openMessage(item)}><i className="is-message"/><div><span>{item.clientName} · {item.projectTitle}</span><strong>{item.kind==="text"?"Client message":String(item.kind||"attachment")}</strong><p>{item.preview}</p></div><aside>{when(item.createdAt)}<b>→</b></aside></button>)}{!messages.length&&<p className="admin-overview-empty">No client messages yet.</p>}</div></section>}
</div>}</main>}