"use client";

import Localized from "../Localized";
import Link from "next/link";

export default function AboutPage(){return <Localized><main className="ref-page page-about">
<section className="ref-hero"><div className="ref-shell ref-hero-grid"><div className="ref-hero-copy"><p className="ref-kicker">ABOUT LINETECH</p><h1>More than technology. A smarter tomorrow.</h1><p>LINETECH is a technology company focused on turning clear ideas into real digital products through disciplined design, engineering and execution.</p><div className="ref-hero-actions"><Link className="ref-btn primary" href="/start" prefetch>Start your line ↗</Link><Link className="ref-btn ghost" href="/projects" prefetch>See our work</Link></div></div><div className="ref-visual" aria-hidden="true"><div className="ref-block a"/><div className="ref-block b"/><div className="ref-block c"/><div className="ref-glow"/></div></div></section>
<section className="ref-section"><div className="ref-shell ref-split"><div className="ref-split-copy"><p className="ref-kicker">THE IDEA</p><h2>A line is the beginning of something real.</h2><p>An idea becomes useful when it is understood, defined, designed, built and launched. LINETECH exists to carry that journey from the first line to a working product.</p><p>Today the company focuses on web development, commerce systems, brand identity and professional digital presence.</p></div><div className="ref-split-visual" aria-hidden="true"/></div></section>
<section className="ref-section"><div className="ref-shell"><div className="ref-head"><div><p className="ref-kicker">OUR PRINCIPLES</p><h2>Clear thinking. Strong execution.</h2></div><p>We keep the company focused on practical principles that improve every project from the first conversation to launch.</p></div><div className="ref-grid">{[["01","Clarity first.","We define the real problem before choosing the technology."],["02","Build for use.","A product is only successful when it works in the real world."],["03","Think long term.","Every project should leave behind a stronger foundation."],["04","Stay disciplined.","Design, scope and execution should serve the outcome."]].map(([n,t,d])=><article className="ref-card" key={n}><span className="num">{n}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
<section className="ref-section"><div className="ref-shell ref-founder"><div><p className="ref-kicker">FOUNDER</p><h2 style={{fontSize:"clamp(38px,4vw,58px)",margin:"10px 0 16px"}}>Mohammed Waleed</h2><p style={{color:"#9ea8b2"}}>Founder & CEO — LINETECH</p></div><div className="ref-founder-card"><span className="ref-meta">FOUNDER STATEMENT</span><h3>Building for the long term.</h3><p style={{color:"#9ea8b2",lineHeight:1.75}}>LINETECH is being built as a long-term technology company focused on useful products, strong systems and work that performs beyond the presentation.</p></div></div></section>
<section className="ref-section"><div className="ref-shell"><div className="ref-head"><div><p className="ref-kicker">THE LINE</p><h2>From idea to impact.</h2></div><p>One continuous journey keeps the work simple, understandable and accountable.</p></div><div className="ref-process"><div><p className="ref-kicker">JOURNEY</p><h3>One line.</h3></div>{[["01","Idea"],["02","Define"],["03","Design"],["04","Build / Launch"]].map(([n,t])=><div key={n}><span className="ref-meta">{n}</span><h3>{t}</h3><p>{n==="01"?"Start with the real idea.":n==="02"?"Make the problem and scope clear.":n==="03"?"Shape the right product experience.":"Turn the line into something real."}</p></div>)}</div></div></section>
<section className="ref-cta"><div className="ref-shell ref-cta-inner"><div><p className="ref-kicker">YOUR IDEA</p><h2>What line do you want to start?</h2><p>Bring the idea. We will help turn it into something real.</p></div><Link className="ref-btn primary" href="/start" prefetch>Contact Us ↗</Link></div></section>
</main></Localized>}
