"use client";

import Localized from "../Localized";
import Link from "next/link";

export default function AboutPage(){return <Localized><main className="ref-page page-about">
<section className="ref-hero"><div className="ref-shell ref-hero-grid"><div className="ref-hero-copy"><p className="ref-kicker">COMPANY</p><h1>A technology company built around systems, products and execution.</h1><p>LINETECH turns business problems and clear ideas into digital products that can be operated, maintained and improved over time.</p><div className="ref-hero-actions"><Link className="ref-btn primary" href="/services" prefetch>Explore Solutions ↗</Link><Link className="ref-btn ghost" href="/projects" prefetch>Case Studies</Link></div></div><div className="ref-visual" aria-hidden="true"><div className="ref-block a"/><div className="ref-block b"/><div className="ref-block c"/><div className="ref-glow"/></div></div></section>

<section className="ref-section"><div className="ref-shell ref-split"><div className="ref-split-copy"><p className="ref-kicker">WHAT LINETECH DOES</p><h2>We turn business problems into digital systems.</h2><p>We focus on web platforms, commerce systems and business software, then support those products with the design and structure they need to work clearly.</p><p>The company is built around product thinking, engineering and practical execution — not around producing isolated screens.</p></div><div className="ref-split-visual" aria-hidden="true"/></div></section>

<section className="ref-section"><div className="ref-shell"><div className="ref-head"><div><p className="ref-kicker">HOW THE COMPANY WORKS</p><h2>Technology decisions connected to the business.</h2></div><p>Every project is treated as a system with users, rules, data, workflows and a clear operating goal.</p></div><div className="ref-grid">{[["01","Product thinking","Define what the product must solve before choosing features."],["02","Engineering","Choose a practical architecture and build for performance and maintainability."],["03","Operations","Design the product around the real workflow behind the interface."],["04","Long-term foundation","Leave the product ready for handover, support and future growth."]].map(([n,t,d])=><article className="ref-card" key={n}><span className="num">{n}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>

<section className="ref-section"><div className="ref-shell"><div className="ref-head"><div><p className="ref-kicker">OUR PRINCIPLES</p><h2>Clear thinking. Strong execution.</h2></div><p>We keep the company focused on practical principles that improve every product from the first conversation to launch.</p></div><div className="ref-grid">{[["01","Clarity first.","We define the real problem before choosing the technology."],["02","Build for use.","A product is only successful when it works in the real world."],["03","Think long term.","Every project should leave behind a stronger foundation."],["04","Stay disciplined.","Design, scope and execution should serve the outcome."]].map(([n,t,d])=><article className="ref-card" key={n}><span className="num">{n}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>

<section className="ref-section"><div className="ref-shell ref-founder"><div><p className="ref-kicker">FOUNDER</p><h2 style={{fontSize:"clamp(38px,4vw,58px)",margin:"10px 0 16px"}}>Mohammed Waleed</h2><p style={{color:"#9ea8b2"}}>Founder & CEO — LINETECH</p></div><div className="ref-founder-card"><span className="ref-meta">FOUNDER STATEMENT</span><h3>Building for the long term.</h3><p style={{color:"#9ea8b2",lineHeight:1.75}}>LINETECH is being built as a long-term technology company focused on useful products, strong systems and work that performs beyond the presentation.</p></div></div></section>

<section className="ref-section"><div className="ref-shell"><div className="ref-head"><div><p className="ref-kicker">OPERATING MODEL</p><h2>From business problem to working system.</h2></div><p>One continuous process keeps product decisions, engineering and delivery connected.</p></div><div className="ref-process"><div><p className="ref-kicker">SYSTEM</p><h3>One clear line.</h3></div>{[["01","Understand"],["02","Define the system"],["03","Build the product"],["04","Deploy and evolve"]].map(([n,t])=><div key={n}><span className="ref-meta">{n}</span><h3>{t}</h3><p>{n==="01"?"Understand the business, users and real operational problem.":n==="02"?"Define roles, data, rules, screens and workflows.":n==="03"?"Design and develop the agreed product with a maintainable foundation.":"Deploy, hand over and prepare the product for the next version."}</p></div>)}</div></div></section>
<section className="ref-cta"><div className="ref-shell ref-cta-inner"><div><p className="ref-kicker">START PROJECT</p><h2>Have a business problem that should become a product?</h2><p>Bring the workflow and the goal. We will help define the system.</p></div><Link className="ref-btn primary" href="/start" prefetch>Start Project ↗</Link></div></section>
</main></Localized>}