"use client";

import Localized from "../Localized";
import Link from "next/link";

const projects=[
  {tag:"E-COMMERCE",title:"Flamingo Park",text:"A mobile-first commerce platform focused on product discovery, customer journeys and operational order flow.",href:"/projects/flamingo-park"},
  {tag:"SERVICES MARKETPLACE",title:"Etqan",text:"A service marketplace concept structured around discovery, trust, categories and scalable operations.",href:"/projects/etqan"},
  {tag:"BUSINESS SYSTEM",title:"LedgerPro",text:"A business platform focused on financial records, workflows and clearer operational visibility.",href:"/projects/ledgerpro"},
];

export default function ProjectsPage(){return <Localized><main className="ref-page page-projects">
<section className="ref-hero"><div className="ref-shell ref-hero-grid"><div className="ref-hero-copy"><p className="ref-kicker">CASE STUDIES</p><h1>Selected systems, not a portfolio gallery.</h1><p>Each case study explains the product problem, system structure and what was actually built.</p><div className="ref-hero-actions"><Link className="ref-btn primary" href="/start" prefetch>Start Project ↗</Link><Link className="ref-btn ghost" href="/services" prefetch>Explore Solutions</Link></div></div><div className="ref-visual" aria-hidden="true"><div className="ref-block a"/><div className="ref-block b"/><div className="ref-block c"/><div className="ref-glow"/></div></div></section>
<section className="ref-section"><div className="ref-shell"><div className="ref-head"><div><p className="ref-kicker">SYSTEMS IN PRACTICE</p><h2>Three different products. Three different operational problems.</h2></div><p>Commerce, marketplace and business software each require different users, data, flows and operating logic.</p></div><div className="ref-projects">{projects.map((p,i)=><article className="ref-project" key={p.title}><div className="ref-project-art"><span className="ref-meta" style={{position:"absolute",left:18,top:16}}>0{i+1}</span></div><div className="ref-project-body"><span className="ref-meta">{p.tag}</span><h3>{p.title}</h3><p>{p.text}</p><Link className="ref-btn ghost" href={p.href} prefetch>View case study ↗</Link></div></article>)}</div></div></section>
<section className="ref-section"><div className="ref-shell"><div className="ref-head"><div><p className="ref-kicker">HOW WE EVALUATE A PRODUCT</p><h2>Business logic before visual polish.</h2></div><p>A strong product has to support the workflow behind the interface, not only look finished on the screen.</p></div><div className="ref-grid">{[["01","Problem","Understand the real operational problem."],["02","System","Define users, rules, states and information flow."],["03","Product","Design and build the working experience."],["04","Operation","Launch with a structure the business can actually run."]].map(([n,t,d])=><article className="ref-card" key={n}><span className="num">{n}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
<section className="ref-cta"><div className="ref-shell ref-cta-inner"><div><p className="ref-kicker">START PROJECT</p><h2>Have an operation that needs a better system?</h2><p>Tell us how the business works today. We will help define what the product should become.</p></div><Link className="ref-btn primary" href="/start" prefetch>Start Project ↗</Link></div></section>
</main></Localized>}