"use client";

import { useLayoutEffect } from "react";

const EXTRA = new Map<string,string>([
  // Global / navigation / actions
  ["Home","الرئيسية"],["Services","الخدمات"],["Projects","المشاريع"],["About","من نحن"],["Contact","تواصل معنا"],["Chat","المحادثة"],["Login","تسجيل الدخول"],["Login / Create Account","تسجيل الدخول / إنشاء حساب"],["Start Your Line","ابدأ خطك"],
  ["Navigation","التنقل"],["Quick Links","روابط سريعة"],["Company","الشركة"],["Privacy","الخصوصية"],["Terms","الشروط"],["FAQ","الأسئلة الشائعة"],["Aden, Yemen","عدن، اليمن"],
  ["Technology for a brighter tomorrow.","تقنية لمستقبل أكثر إشراقًا."],["Every idea starts with a line.","كل فكرة تبدأ بخط."],["View our work","شاهد أعمالنا"],["View services","عرض الخدمات"],["Contact Us ↗","تواصل معنا ↖"],["Start now ↗","ابدأ الآن ↖"],
  ["CLEAN","نظيف"],["MINIMAL","بسيط"],["TECHNICAL","تقني"],["IMPACTFUL","مؤثر"],["FAST","سريع"],["CLEAR","واضح"],["RESPONSIVE","متجاوب"],["SCALABLE","قابل للتوسع"],["FLOW","تدفق"],["IDENTITY","هوية"],["CONSISTENCY","اتساق"],["CLARITY","وضوح"],["PROFILE","ملف شخصي"],["WORK","أعمال"],["VALUE","قيمة"],["PRESENCE","حضور"],

  // Home
  ["Fast, polished company websites and digital experiences built for real business use.","مواقع شركات سريعة ومتقنة وتجارب رقمية مصممة للاستخدام التجاري الحقيقي."],
  ["Commerce flows, dashboards and custom systems shaped around the way your business works.","تجارب تجارة إلكترونية ولوحات تحكم وأنظمة مخصصة مبنية حول طريقة عمل نشاطك."],
  ["Clear visual systems that make a business feel consistent, modern and credible.","أنظمة بصرية واضحة تمنح نشاطك حضورًا متسقًا وحديثًا وموثوقًا."],
  ["Professional personal presentation for careers, portfolios and stronger opportunities.","عرض مهني احترافي للسيرة والأعمال يعزز الحضور والفرص المهنية."],
  ["A mobile-first retail experience for product discovery, orders and customer conversion.","تجربة تجارة تجزئة تركز على الجوال لاكتشاف المنتجات والطلبات وتحويل الاهتمام إلى شراء."],
  ["A services marketplace designed to organize discovery, providers and customer journeys.","سوق خدمات مصمم لتنظيم الاكتشاف ومقدمي الخدمات ورحلة العميل."],
  ["A business system for financial records, workflows and clearer operational visibility.","نظام أعمال للسجلات المالية وسير العمل ورؤية تشغيلية أكثر وضوحًا."],
  ["LINETECH is a technology company that turns ideas into real digital products. We begin with clarity, shape the right solution and build for real-world use.","LINETECH شركة تقنية تحوّل الأفكار إلى منتجات رقمية حقيقية. نبدأ بالوضوح، ونصوغ الحل المناسب، ثم نبنيه للاستخدام الواقعي."],
  ["We define the idea, goals and the real challenge.","نحدد الفكرة والأهداف والتحدي الحقيقي."],["We shape the right structure, scope and direction.","نحدد الهيكل والنطاق والاتجاه المناسب."],["We design, develop and test with precision.","نصمم ونطور ونختبر بدقة."],["We deploy, hand over and support the next step.","نطلق المشروع ونسلمه ونجهز الخطوة التالية."],
  ["Clear communication, a focused scope and work that feels intentional from the first line to launch.","تواصل واضح، ونطاق مركز، وعمل مدروس من أول خط حتى الإطلاق."],
  ["A reliable process, careful decisions and a final product built for real use — not just presentation.","عملية موثوقة، وقرارات مدروسة، ومنتج نهائي مبني للاستخدام الحقيقي لا للعرض فقط."],

  // Services overview
  ["We combine clear product thinking, design and engineering to turn ideas into useful digital products.","نجمع بين التفكير الواضح في المنتج والتصميم والهندسة لتحويل الأفكار إلى منتجات رقمية مفيدة."],
  ["High-performance websites and web products built around clear goals, fast loading and long-term scalability.","مواقع ومنتجات ويب عالية الأداء مبنية حول أهداف واضحة وسرعة تحميل وقابلية للتوسع على المدى الطويل."],
  ["Landing pages / Business websites / Custom web apps","صفحات هبوط / مواقع شركات / تطبيقات ويب مخصصة"],
  ["Commerce experiences and operational systems structured around real customer journeys and business workflows.","تجارب تجارة إلكترونية وأنظمة تشغيلية مبنية حول رحلة العميل وسير عمل النشاط الحقيقي."],
  ["E-commerce / Dashboards / Booking / Custom systems","تجارة إلكترونية / لوحات تحكم / حجوزات / أنظمة مخصصة"],
  ["A focused visual system that gives a business a distinctive, consistent and credible presence.","نظام بصري مركز يمنح النشاط حضورًا مميزًا ومتسقًا وموثوقًا."],
  ["Logo direction / Visual system / Brand guidelines","توجه الشعار / النظام البصري / دليل الهوية"],
  ["Professional presentation designed to communicate experience, work and value with clarity.","عرض مهني مصمم لتوضيح الخبرة والأعمال والقيمة بوضوح."],
  ["CV / Portfolio / Personal presence","سيرة ذاتية / معرض أعمال / حضور شخصي"],
  ["Every engagement follows one clear line so scope, expectations and execution stay aligned.","يتبع كل مشروع خطًا واضحًا واحدًا حتى يبقى النطاق والتوقعات والتنفيذ متوافقة."],
  ["We understand the business, idea and real need.","نفهم النشاط والفكرة والحاجة الحقيقية."],["We define scope, priorities and the right solution.","نحدد النطاق والأولويات والحل المناسب."],["We shape the experience before development begins.","نصوغ التجربة قبل بدء التطوير."],["We develop, test, launch and prepare the next step.","نطور ونختبر ونطلق ونجهز الخطوة التالية."],
  ["Tell us the outcome you need. We will help define the right first line.","أخبرنا بالنتيجة التي تحتاجها، وسنساعدك على تحديد الخط الأول المناسب."],

  // Shared service detail
  ["Every engagement is scoped around the result you need, with the deliverables defined before execution starts.","نحدد نطاق كل مشروع حول النتيجة التي تحتاجها، مع توضيح المخرجات قبل بدء التنفيذ."],
  ["We keep the solution focused instead of adding features that do not serve the project.","نحافظ على تركيز الحل بدل إضافة مزايا لا تخدم المشروع."],
  ["A simple process keeps decisions visible, scope controlled and the final outcome aligned with the original goal.","عملية بسيطة تجعل القرارات واضحة والنطاق مضبوطًا والنتيجة النهائية متوافقة مع الهدف الأصلي."],
  ["Prepare a clear project brief, then continue through the contact channel you choose.","جهّز ملخصًا واضحًا للمشروع، ثم تابع عبر قناة التواصل التي تختارها."],

  // Web development
  ["From focused company websites to custom web applications, we shape the experience around the business goal, then build it for speed, clarity and long-term use.","من مواقع الشركات المركزة إلى تطبيقات الويب المخصصة، نصوغ التجربة حول هدف النشاط ثم نبنيها للسرعة والوضوح والاستخدام طويل المدى."],
  ["Product structure","هيكل المنتج"],["A clear page and feature structure before development starts.","هيكل واضح للصفحات والمزايا قبل بدء التطوير."],["Responsive interface","واجهة متجاوبة"],["A polished experience designed to work across desktop, tablet and mobile.","تجربة متقنة تعمل بسلاسة على الكمبيوتر والتابلت والجوال."],["Development","التطوير"],["Clean implementation focused on performance, usability and maintainability.","تنفيذ نظيف يركز على الأداء وسهولة الاستخدام وقابلية الصيانة."],["Launch readiness","جاهزية الإطلاق"],["Testing, deployment preparation and a clear handover for the next step.","اختبارات وتجهيز للنشر وتسليم واضح للخطوة التالية."],
  ["Companies","الشركات"],["A professional digital presence that explains the business clearly and converts interest into action.","حضور رقمي احترافي يشرح النشاط بوضوح ويحوّل الاهتمام إلى إجراء."],["New products","المنتجات الجديدة"],["A strong first version for an idea that needs to become a usable web product.","نسخة أولى قوية لفكرة تحتاج أن تتحول إلى منتج ويب قابل للاستخدام."],["Existing platforms","المنصات القائمة"],["A clearer, faster or more structured experience for a website that has outgrown its current form.","تجربة أوضح وأسرع وأكثر تنظيمًا لموقع تجاوز شكله الحالي."],
  ["We define the audience, goal and the real job the website needs to do.","نحدد الجمهور والهدف والوظيفة الحقيقية التي يجب أن يؤديها الموقع."],["Structure","الهيكلة"],["We shape pages, flows and priorities before visual design begins.","نحدد الصفحات والتدفقات والأولويات قبل بدء التصميم البصري."],["We develop, refine and test the experience across the required screens.","نطور التجربة ونصقلها ونختبرها على الشاشات المطلوبة."],["We prepare deployment, final checks and the handover for ongoing use.","نجهز النشر والفحوصات النهائية والتسليم للاستخدام المستمر."],

  // E-commerce & systems
  ["We design commerce experiences and operational systems around how customers buy and how teams actually work — keeping the flow clear from the interface to the business process behind it.","نصمم تجارب التجارة والأنظمة التشغيلية حول طريقة شراء العملاء وطريقة عمل الفرق فعليًا، مع إبقاء التدفق واضحًا من الواجهة إلى العمليات خلفها."],
  ["Customer journey","رحلة العميل"],["A clear path from discovery to the action that matters, without unnecessary friction.","مسار واضح من الاكتشاف إلى الإجراء المهم دون تعقيد غير ضروري."],["System structure","هيكل النظام"],["Roles, screens, states and workflows organized around the way the business operates.","أدوار وشاشات وحالات وسير عمل منظم حول طريقة عمل النشاط."],["Commerce experience","تجربة التجارة"],["Product, cart, checkout or ordering flows shaped for clarity and practical use.","تدفقات المنتج والسلة والدفع أو الطلب مصممة للوضوح والاستخدام العملي."],["Operational view","الرؤية التشغيلية"],["Dashboards and management flows that make the system easier to run after launch.","لوحات تحكم وتدفقات إدارة تجعل تشغيل النظام أسهل بعد الإطلاق."],
  ["Retail businesses","أنشطة التجزئة"],["Stores that need a stronger digital buying experience and a clearer order flow.","متاجر تحتاج إلى تجربة شراء رقمية أقوى وتدفق طلبات أوضح."],["Service operations","عمليات الخدمات"],["Businesses that need booking, requests, dashboards or structured internal workflows.","أنشطة تحتاج حجوزات أو طلبات أو لوحات تحكم أو سير عمل داخلي منظم."],["Custom processes","عمليات مخصصة"],["Teams using manual or disconnected steps that can be turned into one focused system.","فرق تستخدم خطوات يدوية أو منفصلة يمكن تحويلها إلى نظام واحد مركز."],
  ["Map the flow","رسم التدفق"],["We understand the customer journey and the operational steps behind it.","نفهم رحلة العميل والخطوات التشغيلية التي تقف خلفها."],["Define the system","تحديد النظام"],["We clarify roles, states, screens and the minimum useful scope.","نوضح الأدوار والحالات والشاشات والحد الأدنى المفيد من النطاق."],["Design & build","التصميم والبناء"],["We shape the interface and implement the agreed workflows.","نصوغ الواجهة وننفذ سير العمل المتفق عليه."],["Test the process","اختبار العملية"],["We validate the end-to-end flow and prepare the system for real use.","نتحقق من التدفق الكامل ونجهز النظام للاستخدام الحقيقي."],

  // Brand identity
  ["We build focused brand identities that make a business feel intentional, consistent and credible across the places customers actually see it.","نبني هويات بصرية مركزة تجعل النشاط يبدو مقصودًا ومتسقًا وموثوقًا في كل نقاط ظهوره أمام العملاء."],
  ["Visual direction","التوجه البصري"],["A focused look and feel that matches the business, audience and positioning.","مظهر وتوجه بصري مركز يتناسب مع النشاط والجمهور وموقع العلامة."],["Logo system","نظام الشعار"],["A practical logo direction with the core versions needed for real-world use.","توجه عملي للشعار مع النسخ الأساسية المطلوبة للاستخدام الواقعي."],["Brand language","لغة الهوية"],["Typography, color and graphic rules that keep the identity consistent.","قواعد الخطوط والألوان والعناصر الرسومية التي تحافظ على اتساق الهوية."],["Usage guidance","إرشادات الاستخدام"],["A simple system that makes future design decisions easier and more coherent.","نظام بسيط يجعل قرارات التصميم المستقبلية أسهل وأكثر اتساقًا."],
  ["New businesses","الأعمال الجديدة"],["A strong first identity for a company that needs to enter the market with clarity.","هوية أولى قوية لشركة تحتاج دخول السوق بوضوح."],["Growing brands","العلامات النامية"],["A more consistent system for a business whose current visuals no longer match its direction.","نظام أكثر اتساقًا لنشاط لم تعد هويته الحالية تعكس توجهه."],["Digital products","المنتجات الرقمية"],["A visual foundation that can move naturally across a website, product and social presence.","أساس بصري ينتقل بسلاسة عبر الموقع والمنتج والحضور على المنصات الاجتماعية."],
  ["We clarify the business, audience, tone and what the identity needs to communicate.","نوضح النشاط والجمهور والنبرة وما يجب أن تعبّر عنه الهوية."],["Direction","الاتجاه"],["We define the visual territory before refining individual elements.","نحدد المجال البصري قبل صقل العناصر الفردية."],["Systemize","بناء النظام"],["We turn the direction into a repeatable logo, type, color and graphic system.","نحوّل التوجه إلى نظام متكامل للشعار والخطوط والألوان والعناصر الرسومية."],["Deliver","التسليم"],["We prepare the agreed assets and practical guidance for consistent use.","نجهز الأصول المتفق عليها وإرشادات عملية للاستخدام المتسق."],

  // CV & Portfolio
  ["We structure professional experience, projects and personal value into a cleaner CV and portfolio presence that is easier to understand and easier to trust.","ننظم الخبرة والمشاريع والقيمة الشخصية في سيرة ومعرض أعمال أوضح وأسهل للفهم وبناء الثقة."],
  ["Content structure","هيكلة المحتوى"],["Experience, skills and projects organized around what matters most to the target opportunity.","تنظيم الخبرة والمهارات والمشاريع حول ما يهم أكثر للفرصة المستهدفة."],["CV presentation","عرض السيرة الذاتية"],["A clean professional document with stronger hierarchy, readability and consistency.","وثيقة احترافية نظيفة بتسلسل بصري ووضوح واتساق أقوى."],["Portfolio structure","هيكلة معرض الأعمال"],["A focused way to present selected work, responsibilities and project context.","طريقة مركزة لعرض الأعمال المختارة والمسؤوليات وسياق المشاريع."],["Digital presence","الحضور الرقمي"],["A clearer foundation for presenting the same professional story across relevant channels.","أساس أوضح لعرض القصة المهنية نفسها عبر القنوات المناسبة."],
  ["Students & graduates","الطلاب والخريجون"],["A first professional presentation that turns academic and project work into a clearer story.","عرض مهني أول يحول العمل الأكاديمي والمشاريع إلى قصة أوضح."],["Professionals","المحترفون"],["A stronger CV or portfolio when experience has grown but the current presentation has not.","سيرة أو معرض أعمال أقوى عندما تنمو الخبرة بينما يبقى العرض الحالي كما هو."],["Specialists & freelancers","المتخصصون والمستقلون"],["A focused portfolio that helps clients or employers understand capabilities quickly.","معرض أعمال مركز يساعد العملاء أو أصحاب العمل على فهم القدرات بسرعة."],
  ["Review","المراجعة"],["We understand the target role, current material and strongest experience.","نفهم الدور المستهدف والمواد الحالية وأقوى الخبرات."],["Prioritize","تحديد الأولويات"],["We decide what should lead, what supports it and what can be removed.","نحدد ما يجب أن يتصدر، وما يدعمه، وما يمكن إزالته."],["Present","العرض"],["We build the hierarchy, wording structure and visual presentation.","نبني التسلسل وهيكل الصياغة والعرض البصري."],["Finalize","الإنهاء"],["We refine consistency and prepare the agreed files for practical use.","نصقل الاتساق ونجهز الملفات المتفق عليها للاستخدام العملي."],

  // Projects overview
  ["Selected work that represents LINETECH's direction: practical products, clear systems and experiences built for real use.","أعمال مختارة تمثل توجه LINETECH: منتجات عملية، وأنظمة واضحة، وتجارب مبنية للاستخدام الحقيقي."],
  ["A mobile-first commerce platform focused on product discovery, customer journeys and operational order flow.","منصة تجارة إلكترونية تركز على الجوال واكتشاف المنتجات ورحلة العميل وتدفق الطلبات التشغيلي."],
  ["A service marketplace concept structured around discovery, trust, categories and scalable operations.","مفهوم لسوق خدمات مبني حول الاكتشاف والثقة والتصنيفات وعمليات قابلة للتوسع."],
  ["A business platform focused on financial records, workflows and clearer operational visibility.","منصة أعمال تركز على السجلات المالية وسير العمل ووضوح العمليات."],
  ["Each project begins with a real problem, a clear user and a result worth building toward.","كل مشروع يبدأ بمشكلة حقيقية، ومستخدم واضح، ونتيجة تستحق البناء من أجلها."],
  ["Our work is evaluated by clarity, usability, performance and how well it supports the business behind it.","نقيّم عملنا بالوضوح وسهولة الاستخدام والأداء ومدى خدمته للنشاط خلفه."],
  ["Understand what needs to change.","نفهم ما الذي يحتاج إلى التغيير."],["Define the simplest strong solution.","نحدد أبسط حل قوي."],["Design and build for real use.","نصمم ونبني للاستخدام الحقيقي."],["Launch with a foundation for growth.","نطلق على أساس يدعم النمو."],["Your project can be the next line.","مشروعك يمكن أن يكون الخط التالي."],["Start with the idea. We will help shape the product.","ابدأ بالفكرة، وسنساعدك على صياغة المنتج."],

  // Shared project detail
  ["The case study focuses on the product structure and implemented capabilities rather than invented performance claims.","تركز دراسة الحالة على هيكل المنتج والقدرات المنفذة بدل ادعاءات أداء غير حقيقية."],
  ["Technology choices support the product requirements, maintainability and deployment needs.","اختيارات التقنية تدعم متطلبات المنتج وقابلية الصيانة واحتياجات النشر."],
  ["What needed to become clearer.","ما الذي كان يحتاج إلى وضوح أكبر."],["Structure before complexity.","الهيكلة قبل التعقيد."],["The working parts.","الأجزاء الفعالة."],["Built on a practical stack.","مبني على حزمة تقنية عملية."],["Have a product that needs a clearer line?","لديك منتج يحتاج إلى خط أوضح؟"],["Start with the problem. We will help shape the right product.","ابدأ بالمشكلة، وسنساعدك على صياغة المنتج المناسب."],

  // Flamingo Park
  ["A mobile-first commerce experience built around product discovery, faster ordering and a clearer operational flow for the store.","تجربة تجارة إلكترونية تركز على الجوال، مبنية حول اكتشاف المنتجات وتسريع الطلبات وتدفق تشغيلي أوضح للمتجر."],
  ["Flamingo Park brings the catalog, product detail, filtering, ordering and store management into one focused digital experience designed for customers using mobile first.","يجمع Flamingo Park الكتالوج وتفاصيل المنتج والتصفية والطلبات وإدارة المتجر في تجربة رقمية واحدة مركزة ومصممة للجوال أولًا."],
  ["The product needed to make a large catalog easier to browse while reducing friction around product choices, orders and the operational work behind them.","كان المنتج بحاجة إلى جعل الكتالوج الكبير أسهل في التصفح مع تقليل التعقيد في خيارات المنتجات والطلبات والعمل التشغيلي خلفها."],
  ["The experience was structured around fast discovery, clear product information, responsive interaction and an admin flow that keeps catalog and order work manageable.","تمت هيكلة التجربة حول الاكتشاف السريع ومعلومات المنتج الواضحة والتفاعل المتجاوب وتدفق إدارة يجعل الكتالوج والطلبات أسهل في التشغيل."],
  ["Catalog & discovery","الكتالوج والاكتشاف"],["Categories, brands, filtering and product browsing structured for a growing catalog.","تصنيفات وعلامات وتصفية وتصفح منتجات مهيأة لكتالوج متنامٍ."],["Product experience","تجربة المنتج"],["Product detail flows for images, sizes, colors, availability and purchase actions.","تدفقات لتفاصيل المنتج تشمل الصور والمقاسات والألوان والتوفر وإجراءات الشراء."],["Order journey","رحلة الطلب"],["A clearer path from product selection to order confirmation and customer follow-up.","مسار أوضح من اختيار المنتج إلى تأكيد الطلب ومتابعة العميل."],["Store operations","عمليات المتجر"],["Admin tools for products, content, customers, orders and store configuration.","أدوات إدارة للمنتجات والمحتوى والعملاء والطلبات وإعدادات المتجر."],

  // Etqan
  ["A services marketplace designed to make finding, comparing and requesting local services clearer for customers and easier to manage operationally.","سوق خدمات مصمم لجعل العثور على الخدمات المحلية ومقارنتها وطلبها أوضح للعملاء وأسهل في الإدارة."],
  ["Etqan organizes providers, categories and service requests into one marketplace experience, with the structure needed to support both customer discovery and platform administration.","ينظم إتقان مقدمي الخدمات والتصنيفات وطلبات الخدمة في تجربة سوق واحدة، مع الهيكل اللازم لدعم اكتشاف العملاء وإدارة المنصة."],
  ["A services marketplace has to make many providers and categories feel simple, while still creating enough structure for trust, discovery and future growth.","يجب أن يجعل سوق الخدمات كثرة مقدمي الخدمات والتصنيفات بسيطة، مع الحفاظ على هيكل كافٍ للثقة والاكتشاف والنمو المستقبلي."],
  ["The product was shaped around clear categories, provider visibility, focused customer journeys and an admin structure that can support the marketplace as it expands.","تم تشكيل المنتج حول تصنيفات واضحة وظهور مقدمي الخدمات ورحلات عميل مركزة وهيكل إدارة يدعم توسع السوق."],
  ["Service discovery","اكتشاف الخدمات"],["Category-driven browsing that helps customers move from a need to relevant providers.","تصفح قائم على التصنيفات يساعد العملاء على الانتقال من الحاجة إلى مقدمي الخدمة المناسبين."],["Provider structure","هيكلة مقدمي الخدمات"],["A consistent way to present service providers, details and the information customers need.","طريقة متسقة لعرض مقدمي الخدمات والتفاصيل والمعلومات التي يحتاجها العملاء."],["Flows for discovering, reviewing and moving toward a service request with less confusion.","تدفقات للاكتشاف والمراجعة والانتقال إلى طلب الخدمة بوضوح أكبر."],["Admin operations","إدارة المنصة"],["Management areas for marketplace content, providers, customers and platform structure.","مساحات إدارة لمحتوى السوق ومقدمي الخدمات والعملاء وهيكل المنصة."],

  // LedgerPro
  ["A business system built to organize financial records, operational workflows and the information teams need to see clearly.","نظام أعمال مبني لتنظيم السجلات المالية وسير العمل والمعلومات التي تحتاج الفرق إلى رؤيتها بوضوح."],
  ["LedgerPro brings core business records and workflows into a structured web platform so information is easier to manage, review and extend as operational needs grow.","يجمع LedgerPro سجلات الأعمال الأساسية وسير العمل في منصة ويب منظمة لتسهيل إدارة المعلومات ومراجعتها وتوسيعها مع نمو الاحتياجات التشغيلية."],
  ["Business records become difficult to manage when information is spread across manual steps, disconnected files and inconsistent workflows.","تصبح سجلات الأعمال صعبة الإدارة عندما تتوزع المعلومات بين خطوات يدوية وملفات منفصلة وسير عمل غير متسق."],
  ["The system was structured around clear entities, repeatable workflows and a practical interface that keeps operational data easier to understand and maintain.","تمت هيكلة النظام حول كيانات واضحة وسير عمل متكرر وواجهة عملية تجعل البيانات التشغيلية أسهل للفهم والصيانة."],
  ["Records structure","هيكلة السجلات"],["Core business and financial records organized into a consistent system.","تنظيم سجلات الأعمال والسجلات المالية الأساسية في نظام متسق."],["Operational workflows","سير العمل التشغيلي"],["Repeatable flows for creating, updating and reviewing day-to-day information.","تدفقات متكررة لإنشاء المعلومات اليومية وتحديثها ومراجعتها."],["Dashboard visibility","وضوح لوحة التحكم"],["Focused views that surface the information needed for clearer operational awareness.","واجهات مركزة تُظهر المعلومات المطلوبة لرؤية تشغيلية أوضح."],["Scalable foundation","أساس قابل للتوسع"],["A web architecture that can support additional business capabilities as requirements develop.","بنية ويب يمكنها دعم قدرات أعمال إضافية مع تطور المتطلبات."],

  // About
  ["LINETECH is a technology company focused on turning clear ideas into real digital products through disciplined design, engineering and execution.","LINETECH شركة تقنية تركز على تحويل الأفكار الواضحة إلى منتجات رقمية حقيقية عبر تصميم وهندسة وتنفيذ منضبط."],
  ["A line is the beginning of something real.","الخط هو بداية شيء حقيقي."],["An idea becomes useful when it is understood, defined, designed, built and launched. LINETECH exists to carry that journey from the first line to a working product.","تصبح الفكرة مفيدة عندما تُفهم وتُحدد وتُصمم وتُبنى وتُطلق. وُجدت LINETECH لتحمل هذه الرحلة من الخط الأول إلى منتج يعمل فعليًا."],["Today the company focuses on web development, commerce systems, brand identity and professional digital presence.","تركز الشركة اليوم على تطوير الويب وأنظمة التجارة والهوية البصرية والحضور الرقمي المهني."],
  ["We keep the company focused on practical principles that improve every project from the first conversation to launch.","نبقي الشركة مركزة على مبادئ عملية تحسن كل مشروع من أول محادثة حتى الإطلاق."],["Clarity first.","الوضوح أولًا."],["We define the real problem before choosing the technology.","نحدد المشكلة الحقيقية قبل اختيار التقنية."],["Build for use.","نبني للاستخدام."],["A product is only successful when it works in the real world.","لا يكون المنتج ناجحًا إلا عندما يعمل في العالم الحقيقي."],["Think long term.","نفكر على المدى الطويل."],["Every project should leave behind a stronger foundation.","يجب أن يترك كل مشروع خلفه أساسًا أقوى."],["Stay disciplined.","نحافظ على الانضباط."],["Design, scope and execution should serve the outcome.","يجب أن يخدم التصميم والنطاق والتنفيذ النتيجة المطلوبة."],
  ["LINETECH is being built as a long-term technology company focused on useful products, strong systems and work that performs beyond the presentation.","نبني LINETECH كشركة تقنية طويلة المدى تركز على منتجات مفيدة وأنظمة قوية وعمل يتجاوز مجرد العرض."],["One continuous journey keeps the work simple, understandable and accountable.","رحلة واحدة متصلة تبقي العمل بسيطًا ومفهومًا وقابلًا للمساءلة."],["Start with the real idea.","ابدأ بالفكرة الحقيقية."],["Make the problem and scope clear.","اجعل المشكلة والنطاق واضحين."],["Shape the right product experience.","صغ تجربة المنتج المناسبة."],["Turn the line into something real.","حوّل الخط إلى شيء حقيقي."],["Bring the idea. We will help turn it into something real.","أحضر الفكرة، وسنساعدك على تحويلها إلى شيء حقيقي."],

  // Start / brief
  ["Start with the idea — even if it is still rough. We will use the brief to turn it into a clear first line.","ابدأ بالفكرة حتى لو كانت ما تزال أولية. سنستخدم الملخص لتحويلها إلى خط أول واضح."],["Fill in what you know. You do not need technical knowledge or every answer yet.","اكتب ما تعرفه. لا تحتاج إلى معرفة تقنية أو إلى امتلاك كل الإجابات الآن."],["Your idea stays in your browser until you choose to copy or share it.","تبقى فكرتك في متصفحك حتى تختار نسخها أو مشاركتها."],["Three short steps help define the real size and direction of the project.","ثلاث خطوات قصيرة تساعد في تحديد حجم المشروع واتجاهه الحقيقي."],["You can start even if budget or timing are not defined yet.","يمكنك البدء حتى لو لم تحدد الميزانية أو الموعد بعد."],
  ["This brief stays on your device. Nothing is sent or stored by this form.","يبقى هذا الملخص على جهازك. لا يتم إرسال أو تخزين أي شيء عبر هذا النموذج."],["About you","معلوماتك"],["Scope","النطاق"],["01 / ABOUT YOU","01 / معلوماتك"],["Who are we building with?","مع من سنبني؟"],["Start with the essentials so the project has a clear owner and communication path.","ابدأ بالأساسيات حتى يكون للمشروع مسؤول واضح وقناة تواصل محددة."],["Your name *","اسمك *"],["Your full name","اسمك الكامل"],["Company / Brand","الشركة / العلامة"],["Optional","اختياري"],["Email or WhatsApp *","البريد أو واتساب *"],["How should we reach you?","كيف يمكننا التواصل معك؟"],["Preferred contact","طريقة التواصل المفضلة"],["WhatsApp","واتساب"],["Email","البريد الإلكتروني"],["Call","مكالمة"],["Either","أي منهما"],["Project type *","نوع المشروع *"],["Select a service","اختر خدمة"],["Continue to project","الانتقال إلى المشروع"],
  ["02 / THE PROJECT","02 / المشروع"],["What needs to become real?","ما الذي يجب أن يتحول إلى واقع؟"],["Tell us the goal, current stage and the few things the solution must do well.","أخبرنا بالهدف والمرحلة الحالية وأهم الأشياء التي يجب أن ينجزها الحل جيدًا."],["Project stage *","مرحلة المشروع *"],["Select current stage","اختر المرحلة الحالية"],["Main goal *","الهدف الرئيسي *"],["Select the main outcome","اختر النتيجة الرئيسية"],["What do you want to build? *","ماذا تريد أن تبني؟ *"],["Describe the idea, problem and final result.","صف الفكرة والمشكلة والنتيجة النهائية."],["Who is it for?","لمن هذا المشروع؟"],["Customers, companies, a team, recruiters, a specific market...","عملاء، شركات، فريق، جهات توظيف، سوق محدد..."],["Must-have features","المزايا الأساسية"],["List the 3–5 things the project cannot work without.","اذكر 3–5 أشياء لا يمكن للمشروع العمل بدونها."],["Existing links / references","روابط / مراجع موجودة"],["Current site, competitor links or examples you like.","الموقع الحالي أو روابط منافسين أو أمثلة تعجبك."],["← Back","رجوع →"],["Continue to scope","الانتقال إلى النطاق"],
  ["03 / SCOPE","03 / النطاق"],["How should we frame the first move?","كيف نحدد الخطوة الأولى؟"],["These details help separate a small focused engagement from a larger product build.","تساعد هذه التفاصيل على التفريق بين مشروع صغير ومركز وبين بناء منتج أكبر."],["Budget range","نطاق الميزانية"],["Launch timing","موعد الإطلاق"],["Anything else we should know?","هل هناك شيء آخر يجب أن نعرفه؟"],["Constraints, preferences, deadlines or context.","قيود أو تفضيلات أو مواعيد نهائية أو سياق إضافي."],["Stage","المرحلة"],["Goal","الهدف"],["Timing","الوقت"],["READY BRIEF","الملخص جاهز"],["Review, copy or share this brief when you are ready to continue with LINETECH.","راجع الملخص أو انسخه أو شاركه عندما تكون مستعدًا للمتابعة مع LINETECH."],["Copy project brief","نسخ ملخص المشروع"],["Copied ✓","تم النسخ ✓"],["Share brief","مشاركة الملخص"],["Preview next step","معاينة الخطوة التالية"],["← Back to project","العودة إلى المشروع →"],
  ["New idea","فكرة جديدة"],["Existing project","مشروع قائم"],["Redesign / rebuild","إعادة تصميم / بناء"],["Improve an existing system","تحسين نظام قائم"],["Sell / generate leads","بيع / جذب عملاء محتملين"],["Bookings / requests","حجوزات / طلبات"],["Internal operations","عمليات داخلية"],["Build credibility","بناء المصداقية"],["Career / portfolio","مسار مهني / معرض أعمال"],["Other","أخرى"],["Need guidance","أحتاج إرشادًا"],["Small focused project","مشروع صغير ومحدد"],["Medium project","مشروع متوسط"],["Large project","مشروع كبير"],["ASAP","في أقرب وقت"],["1–2 months","شهر إلى شهرين"],["3+ months","3 أشهر أو أكثر"],["Flexible","مرن"],
  ["Once the brief is clear, the next step is defining the project and preparing the right execution plan.","عندما يصبح الملخص واضحًا، تكون الخطوة التالية هي تحديد المشروع وإعداد خطة التنفيذ المناسبة."],["You explain what you want to achieve.","تشرح ما الذي تريد تحقيقه."],["We clarify scope, priorities and the right direction.","نوضح النطاق والأولويات والاتجاه المناسب."],["The product structure and next actions become clear.","يصبح هيكل المنتج والخطوات التالية واضحين."],["Execution begins once scope is agreed.","يبدأ التنفيذ بعد الاتفاق على النطاق."],["Make the first line clear, then build from there.","اجعل الخط الأول واضحًا، ثم ابنِ انطلاقًا منه."],

  // FAQ
  ["Common questions about scope, payments, revisions, launch and the way LINETECH approaches project work.","أسئلة شائعة حول النطاق والمدفوعات والتعديلات والإطلاق وطريقة LINETECH في إدارة المشاريع."],["Keep the process clear from the first line.","حافظ على وضوح العملية من الخط الأول."],["If your question is specific to your project, prepare the brief first, then share it through your preferred contact channel.","إذا كان سؤالك خاصًا بمشروعك، جهّز الملخص أولًا ثم شاركه عبر قناة التواصل التي تفضلها."],
  ["How do we start a project?","كيف نبدأ مشروعًا؟"],["Start with the project brief. You can explain the idea in simple language; technical details can be defined after the goal and scope are clear.","ابدأ بملخص المشروع. يمكنك شرح الفكرة بلغة بسيطة، ويمكن تحديد التفاصيل التقنية بعد وضوح الهدف والنطاق."],
  ["Do I need a complete specification before contacting LINETECH?","هل أحتاج إلى مواصفات كاملة قبل التواصل مع LINETECH؟"],["No. A rough idea is enough to begin the conversation. The first step is understanding the outcome, then defining the useful scope.","لا. تكفي فكرة أولية لبدء المحادثة. الخطوة الأولى هي فهم النتيجة المطلوبة ثم تحديد النطاق المفيد."],
  ["How are payments usually structured?","كيف تُقسم المدفوعات عادة؟"],["For project work, the standard structure is 40% to begin, 30% during the project and 30% before final handover, unless a different structure is agreed for the project.","في أعمال المشاريع، التقسيم القياسي هو 40% للبدء، و30% أثناء المشروع، و30% قبل التسليم النهائي، ما لم يتم الاتفاق على تقسيم مختلف."],
  ["How long does a project take?","كم يستغرق المشروع؟"],["Timing depends on the type of work, scope, content readiness and feedback speed. The schedule is defined after the project is understood rather than promising one fixed duration for every project.","يعتمد الوقت على نوع العمل والنطاق وجاهزية المحتوى وسرعة الملاحظات. يتم تحديد الجدول بعد فهم المشروع بدل وعد مدة ثابتة لكل المشاريع."],
  ["Can the scope change after work begins?","هل يمكن تغيير النطاق بعد بدء العمل؟"],["Yes, but changes that affect the agreed scope, timeline or deliverables are reviewed before they are added so the project stays controlled.","نعم، لكن التغييرات التي تؤثر في النطاق أو الجدول أو المخرجات المتفق عليها تتم مراجعتها قبل إضافتها حتى يبقى المشروع منضبطًا."],
  ["Are revisions included?","هل التعديلات مشمولة؟"],["Revisions are handled within the agreed project scope. The exact review stages and what is included are defined before execution begins.","تتم التعديلات ضمن نطاق المشروع المتفق عليه، وتُحدد مراحل المراجعة وما هو مشمول قبل بدء التنفيذ."],
  ["Who handles hosting and deployment?","من يتولى الاستضافة والنشر؟"],["For web projects, deployment can be prepared as part of the project. The exact hosting setup depends on the product and is agreed during planning.","في مشاريع الويب يمكن تجهيز النشر كجزء من المشروع. يعتمد إعداد الاستضافة على المنتج ويتم الاتفاق عليه أثناء التخطيط."],
  ["What happens after launch?","ماذا يحدث بعد الإطلاق؟"],["The handover includes the agreed project assets and launch state. Ongoing maintenance or support can be scoped separately when needed.","يشمل التسليم أصول المشروع المتفق عليها وحالة الإطلاق، ويمكن تحديد الصيانة أو الدعم المستمر بشكل منفصل عند الحاجة."],

  // Privacy / terms
  ["Your information should stay clear and controlled.","يجب أن تبقى معلوماتك واضحة وتحت سيطرتك."],["This page explains how information is handled when you use the LINETECH website and project brief.","توضح هذه الصفحة كيفية التعامل مع المعلومات عند استخدام موقع LINETECH وملخص المشروع."],["The current project brief is designed to keep your typed content in the browser until you choose to copy or share it.","تم تصميم ملخص المشروع الحالي ليبقي المحتوى الذي تكتبه داخل المتصفح حتى تختار نسخه أو مشاركته."],
  ["1. Information you choose to provide","1. المعلومات التي تختار تقديمها"],["2. Technical website data","2. البيانات التقنية للموقع"],["3. Information you send directly","3. المعلومات التي ترسلها مباشرة"],["4. Sharing and selling","4. المشاركة والبيع"],["5. Retention","5. الاحتفاظ بالبيانات"],["6. Changes to this page","6. التغييرات على هذه الصفحة"],
  ["If you use the project brief, you may enter information about yourself, your business or a project. The current brief does not intentionally send that content to LINETECH automatically; it remains in your browser until you choose a copy or share action.","إذا استخدمت ملخص المشروع فقد تدخل معلومات عنك أو عن نشاطك أو مشروعك. لا يرسل الملخص الحالي هذا المحتوى تلقائيًا إلى LINETECH؛ بل يبقى في متصفحك حتى تختار النسخ أو المشاركة."],
  ["Like most hosted websites, infrastructure providers may process technical request information needed to deliver and secure the site, such as IP address, browser information, timestamps and request logs. LINETECH does not use this page to claim access to data it does not actually receive.","مثل أغلب المواقع المستضافة، قد يعالج مزودو البنية التحتية معلومات تقنية لازمة لتقديم الموقع وتأمينه مثل عنوان IP ومعلومات المتصفح والتوقيتات وسجلات الطلبات. لا تدعي LINETECH عبر هذه الصفحة الوصول إلى بيانات لا تستلمها فعليًا."],
  ["If you choose to send project information to LINETECH through a communication channel, that information may be used to understand your request, respond to you, prepare a project scope and manage the working relationship.","إذا اخترت إرسال معلومات المشروع إلى LINETECH عبر قناة تواصل، فقد تُستخدم لفهم طلبك والرد عليك وإعداد نطاق المشروع وإدارة علاقة العمل."],
  ["LINETECH does not intend to sell personal information. Information may only be processed by service providers where needed to operate the website, communications or project delivery, subject to the tools and services actually used.","لا تنوي LINETECH بيع المعلومات الشخصية. وقد تتم معالجة المعلومات بواسطة مزودي الخدمات فقط عند الحاجة لتشغيل الموقع أو التواصل أو تنفيذ المشروع بحسب الأدوات والخدمات المستخدمة فعليًا."],
  ["Information that you send directly may be retained for as long as reasonably needed for communication, project records, legal obligations or legitimate business administration. Browser-only project brief content is controlled by your browser unless you choose to share it.","قد يتم الاحتفاظ بالمعلومات التي ترسلها مباشرة للمدة المعقولة اللازمة للتواصل أو سجلات المشروع أو الالتزامات القانونية أو الإدارة المشروعة للأعمال. أما محتوى ملخص المشروع الموجود في المتصفح فيبقى تحت تحكم متصفحك ما لم تختر مشاركته."],
  ["This privacy information may be updated as the website gains new features, integrations or communication methods. Material changes should be reflected on this page.","قد يتم تحديث معلومات الخصوصية مع إضافة مزايا أو تكاملات أو طرق تواصل جديدة للموقع، وستنعكس التغييرات الجوهرية على هذه الصفحة."],
  ["Clear expectations make better work.","التوقعات الواضحة تصنع عملًا أفضل."],["These terms cover use of the LINETECH website. Individual projects are governed by the scope and agreement accepted for that project.","تغطي هذه الشروط استخدام موقع LINETECH، بينما تخضع المشاريع الفردية للنطاق والاتفاق المعتمد لكل مشروع."],["Project scope, payment stages, deliverables and timelines should be confirmed before execution begins.","يجب تأكيد نطاق المشروع ومراحل الدفع والمخرجات والجداول الزمنية قبل بدء التنفيذ."],
  ["1. Website use","1. استخدام الموقع"],["2. Information on the website","2. المعلومات على الموقع"],["3. Project proposals and scope","3. عروض المشاريع ونطاقها"],["4. Payments","4. المدفوعات"],["5. Client materials and approvals","5. مواد العميل والموافقات"],["6. Intellectual property and handover","6. الملكية الفكرية والتسليم"],["7. External services","7. الخدمات الخارجية"],["8. Changes","8. التغييرات"],
  ["You may use the LINETECH website to learn about the company, services, selected work and how to begin a project. You should not misuse the site, interfere with its operation or attempt unauthorized access to systems or data.","يمكنك استخدام موقع LINETECH للتعرف على الشركة والخدمات والأعمال المختارة وكيفية بدء مشروع. يجب ألا تسيء استخدام الموقع أو تعطل تشغيله أو تحاول الوصول غير المصرح به إلى الأنظمة أو البيانات."],
  ["Website content is intended to describe LINETECH and its services in general terms. Specific project scope, pricing, delivery dates and responsibilities are only confirmed through the agreement for that project.","يهدف محتوى الموقع إلى وصف LINETECH وخدماتها بشكل عام. أما نطاق المشروع المحدد والأسعار ومواعيد التسليم والمسؤوليات فلا يتم تأكيدها إلا عبر اتفاق المشروع نفسه."],
  ["A project begins after the agreed scope, deliverables, timeline and commercial terms are confirmed. Requests outside the agreed scope may require a change to the timeline, price or deliverables before they are added.","يبدأ المشروع بعد تأكيد النطاق والمخرجات والجدول والشروط التجارية المتفق عليها. وقد تتطلب الطلبات خارج النطاق تعديلًا في الوقت أو السعر أو المخرجات قبل إضافتها."],
  ["Unless another structure is agreed in writing, project payments may be organized in stages. The applicable schedule, amount, currency and payment method are confirmed for each project before work begins.","ما لم يتم الاتفاق كتابيًا على غير ذلك، يمكن تنظيم دفعات المشروع على مراحل. ويتم تأكيد الجدول والمبلغ والعملة وطريقة الدفع لكل مشروع قبل بدء العمل."],
  ["Clients are responsible for providing materials, access and approvals needed for their project. Delays in required information or approvals may affect the project schedule.","العملاء مسؤولون عن توفير المواد والصلاحيات والموافقات المطلوبة للمشروع، وقد تؤثر التأخيرات في المعلومات أو الموافقات على الجدول الزمني."],
  ["Ownership, licenses, source files, credentials and handover items depend on the type of project and are defined in the applicable project agreement. Third-party tools, fonts, services and software remain subject to their own licenses and terms.","تعتمد الملكية والتراخيص وملفات المصدر وبيانات الدخول وعناصر التسليم على نوع المشروع وتُحدد في اتفاق المشروع. وتظل أدوات وخطوط وخدمات وبرمجيات الأطراف الخارجية خاضعة لتراخيصها وشروطها."],
  ["Projects and this website may rely on third-party hosting, infrastructure or software. LINETECH cannot control the availability or terms of independent third-party services.","قد تعتمد المشاريع وهذا الموقع على استضافة أو بنية تحتية أو برمجيات من أطراف خارجية، ولا تستطيع LINETECH التحكم في توفر أو شروط الخدمات المستقلة التابعة لتلك الأطراف."],
  ["These website terms may be updated as LINETECH services and website features evolve. The current version is published on this page.","قد يتم تحديث شروط الموقع مع تطور خدمات LINETECH ومزايا الموقع، وتُنشر النسخة الحالية في هذه الصفحة."],

  // Login / account
  ["Sign in if you already have an account, or create one to prepare your LINETECH client workspace.","سجّل الدخول إذا كان لديك حساب، أو أنشئ حسابًا لتجهيز مساحة عملك مع LINETECH."],["PROJECT ACCESS","الوصول للمشروع"],["CLEAR STATUS","حالة واضحة"],["ONE WORKSPACE","مساحة عمل واحدة"],["Need to start a project first?","تريد بدء مشروع أولًا؟"],["CLIENT ACCESS","دخول العميل"],["NEW ACCOUNT","حساب جديد"],["Welcome back.","مرحبًا بعودتك."],["Create your workspace.","أنشئ مساحة عملك."],["Enter your account details to continue.","أدخل بيانات حسابك للمتابعة."],["Create an account to prepare for your LINETECH client workspace.","أنشئ حسابًا لتجهيز مساحة عمل العميل في LINETECH."],["Full name","الاسم الكامل"],["Email address","البريد الإلكتروني"],["Password","كلمة المرور"],["Enter your password","أدخل كلمة المرور"],["Create a password","أنشئ كلمة مرور"],["Confirm password","تأكيد كلمة المرور"],["Repeat your password","أعد كتابة كلمة المرور"],["Remember me","تذكرني"],["Forgot password?","نسيت كلمة المرور؟"],["I agree to the","أوافق على"],["Privacy Policy","سياسة الخصوصية"],["Frontend preview only — account data and credentials are not sent or stored yet.","معاينة واجهة فقط — لا يتم إرسال أو تخزين بيانات الحساب أو معلومات الدخول حاليًا."],
  ["Sign-in UI is ready. Secure authentication will be connected when the backend phase begins.","واجهة تسجيل الدخول جاهزة. سيتم ربط المصادقة الآمنة عند بدء مرحلة الـBackend."],["Account creation UI is ready. Registration will be connected when the backend phase begins.","واجهة إنشاء الحساب جاهزة. سيتم ربط التسجيل عند بدء مرحلة الـBackend."],["Password recovery will be activated with the authentication backend.","سيتم تفعيل استعادة كلمة المرور عند ربط Backend المصادقة."],

  // Chat
  ["Welcome to LINETECH. Send your project questions, files or voice notes here and keep the conversation in one place.","مرحبًا بك في LINETECH. أرسل أسئلة مشروعك وملفاتك ورسائلك الصوتية هنا واحتفظ بالمحادثة في مكان واحد."],["When realtime messaging is connected, this will become the direct conversation between you and the LINETECH team.","عند ربط الرسائل الفورية، ستصبح هذه المحادثة قناة مباشرة بينك وبين فريق LINETECH."],["Search or start new chat","ابحث أو ابدأ محادثة جديدة"],["LINETECH Project Team","فريق مشاريع LINETECH"],["Preview mode","وضع المعاينة"],["Messages stay on this device","الرسائل تبقى على هذا الجهاز"],["Company conversation","محادثة مع الشركة"],["Messages, photos, documents and real voice notes work locally now. Realtime delivery starts when authentication and the backend are connected.","الرسائل والصور والمستندات والرسائل الصوتية تعمل محليًا الآن. يبدأ الإرسال الفوري عند ربط تسجيل الدخول والـBackend."],["This frontend preview stays on your device.","تبقى هذه المعاينة على جهازك."],["Start a conversation","ابدأ محادثة"],["Message deleted","تم حذف الرسالة"],["Photo","صورة"],["Voice message","رسالة صوتية"],["Document","مستند"],["Message","رسالة"],["You: ","أنت: "],["Edit message","تعديل الرسالة"],["Delete for everyone","حذف لدى الطرفين"],["This message was deleted for everyone.","تم حذف هذه الرسالة لدى الطرفين."],["edited","معدلة"],["Drop files here","أفلت الملفات هنا"],["Photos and documents will be added to this conversation","ستتم إضافة الصور والمستندات إلى هذه المحادثة"],["Editing message","تعديل الرسالة"],["Photos","الصور"],["Upload up to 4 images","ارفع حتى 4 صور"],["PDF, Word, Excel and more","PDF وWord وExcel وغيرها"],["Recording real voice","جارٍ تسجيل صوت حقيقي"],["Type a message","اكتب رسالة"],["Edit your message","عدّل رسالتك"],
  ["Saved on this device only — realtime delivery will start when the chat backend is connected.","تم الحفظ على هذا الجهاز فقط — سيبدأ الإرسال الفوري عند ربط Backend المحادثة."],["Message edited in this local preview.","تم تعديل الرسالة في هذه المعاينة المحلية."],["Deleted for everyone in this frontend preview. Realtime deletion will be enforced when the backend is connected.","تم الحذف لدى الطرفين في هذه المعاينة. سيصبح الحذف متزامنًا فعليًا عند ربط الـBackend."],["Preparing image…","جارٍ تجهيز الصورة…"],["This image could not be opened in the preview.","تعذر فتح هذه الصورة في المعاينة."],["Voice recording is not available in this browser.","تسجيل الصوت غير متاح في هذا المتصفح."],["Microphone permission is needed to record a real voice message.","يلزم السماح باستخدام الميكروفون لتسجيل رسالة صوتية حقيقية."],["Voice recording cancelled.","تم إلغاء التسجيل الصوتي."],["Voice note could not be prepared.","تعذر تجهيز الرسالة الصوتية."],["Local preview conversation cleared.","تم مسح محادثة المعاينة المحلية."],["The file works now, but this browser could not keep the full media preview after refresh.","الملف يعمل الآن، لكن المتصفح لم يتمكن من الاحتفاظ بمعاينة الوسائط كاملة بعد التحديث."],
  ["Pause voice message","إيقاف الرسالة الصوتية مؤقتًا"],["Play voice message","تشغيل الرسالة الصوتية"],["Search conversation","بحث في المحادثة"],["Conversation menu","قائمة المحادثة"],["Message actions","خيارات الرسالة"],["Download document","تنزيل المستند"],["Cancel editing","إلغاء التعديل"],["Cancel voice recording","إلغاء التسجيل الصوتي"],["Send voice recording","إرسال التسجيل الصوتي"],["Add attachment","إضافة مرفق"],["Send message","إرسال الرسالة"],["Save edit","حفظ التعديل"],["Record voice message","تسجيل رسالة صوتية"],["Emoji picker can be connected in the next UI pass.","يمكن إضافة منتقي الإيموجي في مرحلة الواجهة التالية."],

  // Thank you / 404
  ["Frontend preview only — no project data has been submitted or stored.","معاينة واجهة فقط — لم يتم إرسال أو تخزين أي بيانات للمشروع."],["This is the confirmation experience LINETECH can use once the final submission flow is connected later. For now, keep your brief ready and use the copy or share actions from the project form.","هذه هي تجربة التأكيد التي يمكن لـLINETECH استخدامها بعد ربط الإرسال النهائي لاحقًا. حاليًا احتفظ بملخصك جاهزًا واستخدم النسخ أو المشاركة من نموذج المشروع."],["Back to Project Brief ↗","العودة إلى ملخص المشروع ↖"],["Your idea is structured into a clear starting point.","تم تنظيم فكرتك في نقطة بداية واضحة."],["Scope, priorities and the right solution are clarified.","يتم توضيح النطاق والأولويات والحل المناسب."],["Execution begins once the project direction is agreed.","يبدأ التنفيذ بعد الاتفاق على اتجاه المشروع."],["The page may have moved, the address may be wrong, or the route does not exist yet. Start again from a clear line.","قد تكون الصفحة نُقلت أو العنوان غير صحيح أو المسار غير موجود بعد. ابدأ من جديد بخط واضح."],

  // Attributes / placeholders / accessibility
  ["LINETECH home","الصفحة الرئيسية لـ LINETECH"],["Choose account action","اختر إجراء الحساب"],["Your full name","اسمك الكامل"],["you@company.com","you@company.com"],["Optional","اختياري"],["Search LINETECH","بحث LINETECH"],["Close search","إغلاق البحث"],["Toggle navigation","فتح أو إغلاق القائمة"],["Primary navigation","التنقل الرئيسي"],["Mobile navigation","تنقل الجوال"],["Search","بحث"],["Message actions","خيارات الرسالة"],["Shared image","صورة مشتركة"]
]);

const ATTRIBUTES = ["placeholder","title","aria-label"] as const;

function normalize(value:string){return value.trim().replace(/\s+/g," ");}
function translate(value:string){return EXTRA.get(normalize(value)) || null;}

function shouldSkip(node:Text){
  const parent=node.parentElement;
  if(!parent || parent.closest("script,style,noscript,code,pre,[data-no-translate]")) return true;
  if(parent.matches(".chat-message-row.client .chat-bubble > p")) return true;
  return false;
}

function replaceText(node:Text){
  if(shouldSkip(node)) return;
  const current=node.nodeValue||"";
  const translated=translate(current);
  if(!translated) return;
  const leading=current.match(/^\s*/)?.[0]||"";
  const trailing=current.match(/\s*$/)?.[0]||"";
  node.nodeValue=`${leading}${translated}${trailing}`;
}

function replaceAttributes(element:Element){
  if(element.closest("[data-no-translate]")) return;
  ATTRIBUTES.forEach(name=>{
    const current=element.getAttribute(name);
    if(!current) return;
    const translated=translate(current);
    if(translated && translated!==current) element.setAttribute(name,translated);
  });
}

function scan(root:Node){
  if(root.nodeType===Node.TEXT_NODE){replaceText(root as Text);return;}
  if(root.nodeType!==Node.ELEMENT_NODE && root.nodeType!==Node.DOCUMENT_NODE) return;
  if(root.nodeType===Node.ELEMENT_NODE) replaceAttributes(root as Element);
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
  let node:Node|null;
  while((node=walker.nextNode())) replaceText(node as Text);
  (root as ParentNode).querySelectorAll?.("[placeholder],[title],[aria-label]").forEach(replaceAttributes);
}

export default function ArabicSupplement(){
  useLayoutEffect(()=>{
    if(window.localStorage.getItem("linetech-language-v1")==="en") return;
    scan(document.body);
    const observer=new MutationObserver(mutations=>{
      mutations.forEach(mutation=>{
        if(mutation.type==="characterData") replaceText(mutation.target as Text);
        mutation.addedNodes.forEach(scan);
        if(mutation.type==="attributes" && mutation.target instanceof Element) replaceAttributes(mutation.target);
      });
    });
    observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:[...ATTRIBUTES]});
    return ()=>observer.disconnect();
  },[]);
  return null;
}
