import ProjectBriefForm from "./ProjectBriefForm";
import "./start.css";

export const metadata={title:"Start Your Line",description:"Start a project with LINETECH and turn your idea into a clear digital product brief."};

export default function StartPage(){return <main className="ref-page">
<header className="ref-nav ref-shell"><a className="ref-brand" href="/"><span className="ref-mark"><i/><b/></span><strong>LINETECH</strong></a><nav className="ref-nav-links"><a href="/">Home</a><a href="/services">Services</a><a href="/projects">Projects</a><a href="/about">About</a><a className="active" href="/start">Contact</a></nav><div className="ref-nav-end"><span className="ref-search" aria-hidden="true">⌕</span><a className="ref-button light" href="#brief">Start Your Line <span>→</span></a></div></header>
<section className="ref-hero"><div className="ref-shell ref-hero-grid"><div className="ref-hero-copy"><p className="ref-kicker">START YOUR LINE</p><h1>Tell us what you want to build.</h1><p>Start with the idea — even if it is still rough. We will use the brief to turn it into a clear first line.</p><div className="ref-hero-actions"><a className="ref-btn primary" href="#brief">Start the brief ↘</a><a className="ref-btn ghost" href="/services">View services</a></div></div><div className="ref-visual" aria-hidden="true"><div className="ref-block a"/><div className="ref-block b"/><div className="ref-block c"/><div className="ref-glow"/><div className="ref-visual-label">IDEA<br/>DEFINE<br/>NEXT STEP<br/>BUILD</div></div></div></section>
<section id="brief" className="ref-section"><div className="ref-shell ref-form-wrap"><div className="ref-form-side"><p className="ref-kicker">PROJECT BRIEF</p><h2>One clear line before we build.</h2><p>Fill in what you know. You do not need technical knowledge or every answer yet.</p><div className="ref-list" style={{marginTop:32}}>{[["01","Your idea stays in your browser until you choose to copy or share it."],["02","The brief helps clarify scope before execution."],["03","You can start even if budget or timing are not defined yet."]].map(([n,t])=><div className="ref-row" style={{gridTemplateColumns:"50px 1fr",padding:"18px 0"}} key={n}><span className="ref-meta">{n}</span><p>{t}</p></div>)}</div></div><ProjectBriefForm/></div></section>
<section className="ref-section"><div className="ref-shell"><div className="ref-head"><div><p className="ref-kicker">WHAT HAPPENS NEXT</p><h2>A simple path forward.</h2></div><p>Once the brief is clear, the next step is defining the project and preparing the right execution plan.</p></div><div className="ref-grid">{[["01","Idea","You explain what you want to achieve."],["02","Define","We clarify scope, priorities and the right direction."],["03","Plan","The product structure and next actions become clear."],["04","Build","Execution begins once scope is agreed."]].map(([n,t,d])=><article className="ref-card" key={n}><span className="num">{n}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
<section className="ref-cta"><div className="ref-shell ref-cta-inner"><div><p className="ref-kicker">LINETECH</p><h2>Every idea starts with a line.</h2><p>Make the first line clear, then build from there.</p></div><a className="ref-btn primary" href="#brief">Start now ↗</a></div></section>
<footer className="ref-footer ref-shell"><div className="ref-footer-grid"><div><a className="brand" href="/"><span className="mark"><i/><b/></span><span>LINETECH</span></a><p>Every idea starts with a line.</p></div><div><h4>Company</h4><a href="/about">About</a><a href="/projects">Projects</a></div><div><h4>Services</h4><a href="/services">Web Development</a><a href="/services">Brand Identity</a><a href="/services">CV & Portfolio</a></div><div><h4>Location</h4><span>Aden, Yemen</span></div></div><div className="ref-footer-bottom"><span>© 2026 LINETECH</span><span>IDEA → DEFINE → BUILD → IMPACT</span></div></footer>
</main>}